version: '3.4'

services:
  eveatherdev:
    image: eveatherdev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3040:3040
