version: '3.4'

services:
  staticwebsitetemplate:
    image: staticwebsitetemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3040:3040
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
